apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/istio_1.22.7
  prune: true
  patches:
    - patch: |-
        apiVersion: v1
        kind: Namespace
        metadata:
          name: istio-system
          labels:
            topology.istio.io/network: network-app